from abc import ABC, abstractmethod


class RiskModel(ABC):
    """
    Abstract interface for an RiskModel callable.

    A derived-class instance of RiskModel takes in an Asset
    Universe and an optional DataHandler instance in order
    to modify weights on Assets generated by an AlphaModel.

    These adjusted weights are used within the PortfolioConstructionModel
    to generate new target weights for the portfolio.

    Implementing __call__ produces a dictionary keyed by
    Asset and with a scalar value as the signal.
    """

    @abstractmethod
    def __call__(self, dt, weights):
        """
        Adjust the target weights generated by an AlphaModel according
        to the risk constraints of this model.

        Parameters
        ----------
        dt : `pd.Timestamp`
            The time 'now' used to obtain appropriate data for the
            risk adjustment.
        weights : `dict{str: float}`
            The Asset symbol keyed target weights to adjust.

        Returns
        -------
        `dict{str: float}`
            The Asset symbol keyed risk-adjusted target weights.
        """
        raise NotImplementedError(
            "Should implement __call__()"
        )
